# Generated by Django 5.2.6 on 2025-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='final_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
