# Generated by Django 5.2.6 on 2025-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_auction', '0002_alter_auction_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
