# Generated by Django 5.2.6 on 2025-10-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_auction', '0003_alter_auction_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='offers',
            field=models.ManyToManyField(related_name='auctions', to='company_auction.offer'),
        ),
    ]
