# Generated by Django 5.2.6 on 2025-10-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_auction', '0004_auction_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='offers',
        ),
    ]
